<a href="https://colab.research.google.com/github/6230204513/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ 

## `list()`
การนำข้อมูลมาต่อๆกัน
list คือตัวเก็บข้อมูลรวมกันอย่างง่าย 
- เก็บอะไรก็ได้
- ลำดับของการเก็บมีความสำคัญ



In [ ]:
list_a = [1,2,3,4,5,6] # list ใช้ [ ] squate brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14,list_a] #สามารถเก็บข้อมูลอะไรก็ได้ และลำดับมีความสำคัญไม่สามารถสลับกันได้

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list
- ลำดับเริ่มจาก 0

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[-1] # index -1 คือตัวสุดท้ายของ list

6

In [ ]:
list_a[-4] # index ติดลบ คือ เริ่มนับจากหลังมาหน้า

3

### การสร้าง ```list()```



In [ ]:
list_x1 = [] # แบบที่1
list_x2 = list() # แบบที่2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```



In [ ]:
list_x1.append(2) # 2 ถูกแทรกลงไปใน list_x1 ดังนั้น ต้อง run list_x1 ใหม่

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4, 4, 4]


### ลบสมาชิกจาก list

In [ ]:
list_x1.pop() # ผลลัพธ์คือตัวที่ตัดทิ้ง

4

In [ ]:
list_x1

[2, 4, 4]

In [ ]:
list_x1.pop()
print(list_x1)

[2, 4]


In [ ]:
list_x2.append('ha') # run 3 ครั้ง แต่ลบตัวที่ run ครั้งแรกไป

In [ ]:
list_x2

['ha', 'ha', 'ha']

In [ ]:
list_x2.pop()
print(list_x2)

['ha', 'ha']


### `len` ตรวจสอบจำนวนสมาชิกของ list



In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculyt of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### List Slicing






`list [จุดเริ่มต้น(ทึบ):จุดสุดท้าย(โปร่ง)]`

`list [จุดเริ่มต้น(ทึบ):จุดสุดท้าย(โปร่ง):step]`

#### : colon

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[-3:] # colon -> a:ช่องว่าง ใช้เมื่อต้องการจาก a ถึง จุดสุดท้าย

[4, 5, 6]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

####step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### `range()`



In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
range(21)

range(0, 21)

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW 2
▶ คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม) ◀

โจทย์ที่กำหนด
- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
#ตัวอย่าง 01:02:03

a = (1*60*60) + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [ ]:
#ข้อ 1 12:30:15
A = '12:30:15' #เวลา 12:30:15 เป็น string และกำหนดให้เป็น A
str_A = A.split(':') # แยก 12:30:15 ออกจากกันโดยใช้คำสั่ง split() แยกเป็น string 'ชั่วโมง' 'นาที' และ'วินาที' 
# ค่าที่แยกก่อนหน้านี้เป็น string ต้องแปลงให้เป็น int ก่อนถึงจะนำมาแปลง(คูณและบวก)เป็นวินาทีได้
a0 = int(str_A[0])
a1 = int(str_A[1])
a2 = int(str_A[2])
Ans1 = a0*60*60 + a1*60 + a2 #หรือเขียนรวมเป็น Ans1 = int(str_A[0])*60*60 + int(str_A[1])*60 + int(str_A[2])เลยก็ได้
print(f'12:30:15 แปลงเป็นวินาที ได้ {Ans1} วินาที' ) #แสดงผลลัพธ์

12:30:15 แปลงเป็นวินาที ได้ 45015 วินาที


In [ ]:
#ข้อ 2 13:41:07
B = '13:41:07'
str_B = B.split(':')
b0 = int(str_B[0])
b1 = int(str_B[1])
b2 = int(str_B[2])
Ans2 = b0*60*60 + b1*60 + b2
print(f'13:41:07 แปลงเป็นวินาที ได้ {Ans2} วินาที' )

13:41:07 แปลงเป็นวินาที ได้ 49267 วินาที


In [ ]:
#ข้อ 3 09:11:50
C = '09:11:50'
str_C = C.split(':')
c0 = int(str_C[0])
c1 = int(str_C[1])
c2 = int(str_C[2])
Ans3 = c0*60*60 + c1*60 + c2
print(f'09:11:50 แปลงเป็นวินาที ได้ {Ans3} วินาที' )

09:11:50 แปลงเป็นวินาที ได้ 33110 วินาที


In [ ]:
#ข้อ 4 21:30:15
D = '21:30:15'
str_D = D.split(':')
d0 = int(str_D[0])
d1 = int(str_D[1])
d2 = int(str_D[2])
Ans4 = d0*60*60 + d1*60 + d2
print(f'21:30:15 แปลงเป็นวินาที ได้ {Ans4} วินาที' )

21:30:15 แปลงเป็นวินาที ได้ 77415 วินาที


In [ ]:
#ข้อ 5 03:10:15
E = '03:10:15'
str_E = E.split(':')
e0 = int(str_E[0])
e1 = int(str_E[1])
e2 = int(str_E[2])
Ans5 = e0*60*60 + e1*60 + e2
print(f'03:10:15 แปลงเป็นวินาที ได้ {Ans5} วินาที' )

03:10:15 แปลงเป็นวินาที ได้ 11415 วินาที


##Dictionary

- คล้าย list()
- index เป็นออะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

In [ ]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # {} Curly brackets

### การชี้ สมาชิกใน Dictionary

In [ ]:
dict_a[1]

'Happy'

In [ ]:
dict_a['N']

'New'

In [ ]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [ ]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [ ]:
dict_a['N'] = 'NNNEEEEWWW' # เมื่อมีการใช้ index ซ้ำ จะมีการอัพเดตเป็นค่าสมาชิกใหม่

In [ ]:
dict_a # 'N' เปลี่ยนจาก 'New' เป็น 'NNNEEEEWWW'

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNEEEEWWW'}

##Numpy Array

- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2มิติ ก็มองเป็น Matrix)

In [ ]:
import numpy

In [ ]:
arr_a = numpy.array([1,2,3,4,5])

In [ ]:
arr_a

array([1, 2, 3, 4, 5])

In [ ]:
list_A = [1,2,3,4,5]
arr_a = numpy.array(list_A)
print(arr_a)


[1 2 3 4 5]


In [ ]:
list_A

[1, 2, 3, 4, 5]

In [ ]:
arr_a[0]

1

In [ ]:
list_A[0]

1

In [ ]:
5*arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [ ]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arr_b = numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a)

[1 2 3 4 5]


In [ ]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [ ]:
import numpy as np

In [ ]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2_z.shape

(2, 3)

### np.zero()

In [ ]:
arr2_3_5_0 = np.zeros((3,5))
print(arr2_3_5_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2_3_5_0[1,2] = 9 # กำหนดค่าใน list()

In [ ]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2_3_5_0[1,2] # ชี้ค่าใน list()

9.0

In [ ]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### `np.ones()`



In [ ]:
arr2_4_5_1 = np.ones((4,5))

In [ ]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr2_4_5_200 = 200*np.ones((4,5))

In [ ]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operation

#### การบวก ลบ matrix $M\pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน
ถ้า shape ไม่เท่ากันจะบวกไม่ได้

In [ ]:
arr2_4_5_200 + arr2_3_5_0 # การบวก ลบ matrix shape ต้องเท่ากัน

ValueError: ignored

In [ ]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix

- $aM$ scalar คูณ matrix (คูณกระจายเข้าไปทุกตัว)
- $M\times M$ matrix คูณ matrix (แถว คูณ หลัก)

$aM$

In [ ]:
5*arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times M$ (dot product)
- (m,n) $\times$ (n,o) = (m,o) (Shape)

In [ ]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [ ]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [ ]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [ ]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

In [ ]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [ ]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

In [ ]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [ ]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [ ]:
mat_a * mat_b #คูณตำแหน่งเดียวกัน ไม่ตรงตามหลักของ matrix

In [ ]:
mat_a * mat_b

array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [ ]:
mat_X = np.dot(mat_c,mat_b)

In [ ]:
mat_X

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [ ]:
mat_X[:2,:2] #ตัดมาเฉพาะส่วนที่ต้องการ

array([[ 8, 16],
       [16, 32]])

## HW 3


1. สร้าง array ที่เป็นรูป ต้น Christmas 
2. sclice เลข 1 ออกจาก array HW3 แค่ครั้งเดียว

In [ ]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

###ข้อ1

In [ ]:
import numpy as np

In [ ]:
x_mas = np.ones((20,13))
x_mas

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 

In [ ]:
x_mas[0,6] = 99
x_mas[1:2,5:8:2] = 99
x_mas[3:4,5:8] = 99
x_mas[4:5,4:9] = 99
x_mas[5:6,5:8] = 99
x_mas[6:7,4:9] = 99
x_mas[7:8,3:10] = 99
x_mas[8:9,4:9] = 99
x_mas[9:10,3:10] = 99
x_mas[10:11,4:9] = 99
x_mas[11:12,3:10] = 99
x_mas[12:13,2:11] = 99
x_mas[13:14,3:10] = 99
x_mas[14:15,2:11] = 99
x_mas[15:17,1:12] = 99
x_mas[1:,6] = 11
x_mas[2,6] = 99
x_mas[17:,5:8:2] = 88

x_mas

array([[ 1.,  1.,  1.,  1.,  1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 99., 11., 99.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 99., 11., 99.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 11., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 99., 11., 99.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 11., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 11., 99., 99., 99.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 11., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 11., 99., 99., 99.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 11., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 11., 99., 99., 99.,  1.,  1.,  1.],
       [ 1.,  1., 99., 99., 99., 99., 11., 99., 99., 99., 99.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 

###ข้อ2

In [ ]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])